name: camiramadashboard
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

# Project version
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.5.3

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  theme_provider: ^0.6.0
  flutter_charts: ^0.5.2
  get: ^4.6.6
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  flutter_dotenv: ^5.2.1

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter settings
flutter:
  uses-material-design: true

  # Assets
  assets:
    - images/a_dot_burr.jpeg

  
